### ISSUE TITLE
Docker failed to start chrome

### ISSUE THREAD

**Issue by maxwu** [maxwu/cucumber-java-toy#4]
Building docker and get an error of chrome crash.
```
docker build --shm-size=512m -t maxwu/cucumber-jvm-toy:onbuild .
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar (37 KB at 113.0 KB/sec)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.maxwu.jrefresh.greenHook.GreenHookTest
GreenHook Proxy starts.
Checking Annotation: @org.maxwu.jrefresh.greenHook.GreenHook(value=)
Interceptor found Annotation, add method to GreenHook map list: public void org.maxwu.jrefresh.greenHook.SurrogateHello.setUpTest()
>> SurrogateHello setUpTest()!
--End--of--Invoke--Proxy--
>> Not a green hook in tearDown.
--End--of--Invoke--Proxy--

GreenHook Reflect starts.
>> SurrogateHello setUpTest()!

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.558 sec
Running org.maxwu.jrefresh.selenium.TemperatureConverterTest
Feature: Browse the temperature converter page
  As a developer,
  In order to convert temperature
  I want to enter number and check result on google search page "temperature convertor".
2017-01-30-22_11_45 #460201727 TemperatureConverterCalStepdef, [Open Temperature Convertor] starts, passed
log4j:WARN No appenders could be found for logger (io.github.bonigarcia.wdm.BrowserManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Starting ChromeDriver 2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320) on port 20299
Only local connections are allowed.
Jan 30, 2017 10:11:51 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Jan 30, 2017 10:12:51 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
**** Created Web Driver #841537936****
Failure in before hook:TemperatureConverterCalStepdef.setUp(Scenario)
Message: org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.43-boot2docker x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 62 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: '41eb22220eb1', ip: '172.17.0.5', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.43-boot2docker', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=unknown error: Chrome failed to start: crashed
  (Driver info: chromedriver=2.27.440175 (9bc1d90b8bfa4dd181fbbf769a5eb5e575574320),platform=Linux 4.4.43-boot2docker x86_64), platform=ANY}]
Session ID: 3e2ff1ff60aac80e71369b737fde936e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:822)
	at org.maxwu.jrefresh.selenium.stepdefs.TemperatureConverterCalStepdef.setUp(TemperatureConverterCalStepdef.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.java.JavaHookDefinition.execute(JavaHookDefinition.java:60)
	at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
	at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
	at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:202)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:40)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```

**Comment by khalistan** [comment]
I am facing same issue but its not related to this project. I think it should be on Docker. BTW have you tried to start Firefox in same container?
