### ISSUE TITLE
Browser crash reported on 32bit Ubuntu 14 Linux

### ISSUE THREAD

**Issue by maxwu** [maxwu/cucumber-java-toy#7]
Chrome tab crash spot.
http://jenkins.maxwu.me/job/Cucumber_Jvm_Selenium_Toy/17/testReport/junit/(root)/Scenario_%20Open%20Temperature%20Convertor/Scenario__Open_Temperature_Convertor/

```
Starting ChromeDriver 2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4) on port 9227
Only local connections are allowed.
Feb 20, 2017 1:02:34 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Attempting bi-dialect session, assuming Postel's Law holds true on the remote end
Feb 20, 2017 1:02:34 AM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
**** Created Web Driver #30057808****
Failure in before hook:TemperatureConverterPageStepDef.setUp(Scenario)
Message: org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Linux 2.6.32-042stab120.18 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 14 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'
System info: host: 'maxwu', ip: '104.224.136.48', os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-042stab120.18', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=session not created exception
from tab crashed
  (Session info: chrome=48.0.2564.116)
  (Driver info: chromedriver=2.21.371459 (36d3d07f660ff2bc1bf28a75d1cdabed0983e7c4),platform=Linux 2.6.32-042stab120.18 x86), platform=ANY}]
Session ID: 55d40b642a275ba583eb6ee9e6d53d31
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:822)
	at org.maxwu.jrefresh.selenium.stepdefs.TemperatureConverterPageStepDef.setUp(TemperatureConverterPageStepDef.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by maxwu** [comment]
Remove below code from PageObject constructor but implement the maximized window behavior with ChromeOptions object.
```java
driver.manage().window().maximize();
``` 
Replace above code in PageObject with below logics in driver factory design.

```java
       options = new ChromeOptions();
        // To fix browser crash issue
        options.addArguments("--start-maximized");
        ChromeDriverManager.getInstance().setup();
        WebDriver driver = (null==options)? new ChromeDriver(): new ChromeDriver(options);

```
