### ISSUE TITLE
Browser hangs up when testing on 32bit Ubuntu Linux VPS

### ISSUE THREAD

**Issue by maxwu** [maxwu/cucumber-java-toy#8]
This happens frequently on the 32bit Ubuntu Linux Jenkins environment, no matter upgrading to chromium-browser 55 and ChromeDriver latest 2.27. 
A similar hanging up does not happen on circle-ci docker environment but randomly about 50% on travis-CI docker cloud testing environment. Both are 64bit Ubuntu docker image.
http://jenkins.maxwu.me/job/Cucumber_Jvm_Selenium_Toy/31/testReport/junit/(root)/%7C%20-100%20%7C%20-148%20%7C/___100____148__/
```
org.openqa.selenium.TimeoutException: timeout: cannot determine loading status
from timeout: Timed out receiving message from renderer: -600.008
  (Session info: chrome=55.0.2883.11)
  (Driver info: chromedriver=2.25.426927 (d0803376130bda68eb594d02ebaca4609e3f899e),platform=Linux 2.6.32-042stab120.18 x86) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 900.74 seconds
Build info: version: '3.1.0', revision: 'b94c902', time: '2017-02-16 12:21:31 -0800'
System info: host: 'jenkins', ip: '104.224.136.48', os.name: 'Linux', os.arch: 'i386', os.version: '2.6.32-042stab120.18', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.25.426927 (d0803376130bda68eb594d02ebaca4609e3f899e), userDataDir=/tmp/.org.chromium.Chromium.auFTt4}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=55.0.2883.11, platform=LINUX, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=true, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 64463c793b65a1f95383edd756abda17
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:216)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:168)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:635)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteNavigation.refresh(RemoteWebDriver.java:910)
```

**Comment by maxwu** [comment]
After testing a various combination with table, here is the solution. Using ChromeOptions to disable DNS pre-fetch and authorize all plugins by default. 

```java
options = new ChromeOptions();
// To fix browser crash issue
options.addArguments("--start-maximized");
// To fix browser hanging-up issue
options.addArguments("--dns-prefetch-disable");
options.addArguments("--always-authorize-plugins");
ChromeDriverManager.getInstance().setup();
WebDriver driver = new ChromeDriver(options);
```
