### ISSUE TITLE
WebDriver.getTitle() returns partial url instead

### ISSUE THREAD

**Issue by maxwu** [maxwu/cucumber-java-toy#9]
With Chrome Browser `Version 56.0.2924.87 (64-bit)` and ChromeDriver 2.27.440174 on Mac 10.11.6, the getTitle() call returns url contents instead of title string. 

```
... com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 org.maxwu.jrefresh.selenium.BlogCommentTest
Case a01checkComments starts.
Arch=64
Starting ChromeDriver 2.27.440174 (e97a722caafc2d3a8b807ee115bfb307f7d2cfd9) on port 1773
Only local connections are allowed.
Feb 24, 2017 11:01:12 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
**** Created Web Driver #243194708****
**** Destroying Web Driver #243194708****
Case a01checkComments fails.

org.maxwu.jrefresh.selenium.pageObjects.WrongPageException: Wrong Title with Pattern ".*Max.*", title=maxwu.me, url=http://maxwu.me/2016/10/02/dropme/

	at org.maxwu.jrefresh.selenium.pageObjects.PageBase.checkTitle(PageBase.java:45)
	at org.maxwu.jrefresh.selenium.pageObjects.PageBase.checkTitle(PageBase.java:55)
	at org.maxwu.jrefresh.selenium.pageObjects.BlogCommentPage.<init>(BlogCommentPage.java:39)
	at org.maxwu.jrefresh.selenium.BlogCommentTest.setUp(BlogCommentTest.java:40)
```

**Comment by maxwu** [comment]
Fixed. It is an environment issue. The ShadowSock client is launched incidentally but via an invalid proxy setting record. Therefore, the WebDriver reported partial URL (removed protocol header like http:// or https://) as title.
